// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectOrigin.EntityFrameworkCore;

namespace ProjectOrigin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230518034622_relacion")]
    partial class relacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProjectOrigin.Models.Entities.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumeroTarjeta")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("ProjectOrigin.Models.Entities.Registros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CodigoOperacion")
                        .HasColumnType("int");

                    b.Property<long>("NumeroTarjeta")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OperacionTiempo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("ProjectOrigin.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumeroTarjeta")
                        .HasColumnType("bigint");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("NumeroTarjeta");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("ProjectOrigin.Models.Entities.Usuario", b =>
                {
                    b.HasOne("ProjectOrigin.Models.Entities.Cuenta", "Cuenta")
                        .WithOne("Usuario")
                        .HasForeignKey("ProjectOrigin.Models.Entities.Usuario", "NumeroTarjeta")
                        .HasPrincipalKey("ProjectOrigin.Models.Entities.Cuenta", "NumeroTarjeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("ProjectOrigin.Models.Entities.Cuenta", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
